name: jacred

services:
  jacred:
    image: matrix37/jacred:latest
    container_name: jacred
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - /home/dockers/jacred/jacred-config:/app/config
      - /mnt/sda1/jacred/jacred-data:/app/Data
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - UMASK=0027
    healthcheck:
      test: [ "CMD", "curl", "-f", "-s", "--max-time", "10", "http://127.0.0.1:9117/health" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: "4"
